//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhoanVay
    {
        public int SoKV { get; set; }
        public int SoTK { get; set; }
        public System.DateTime NgayVay { get; set; }
        public System.DateTime NgayHan { get; set; }
        public double SoTienVay { get; set; }
        public int TinhTrang { get; set; }
        public int LoaiKhoanVay { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
