//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheTinDung
    {
        public int MaTTD { get; set; }
        public int SoTK { get; set; }
        public string TenChuThe { get; set; }
        public double SoDu { get; set; }
        public double HanMuc { get; set; }
        public int TrangThai { get; set; }
        public System.DateTime NgayMoThe { get; set; }
        public System.DateTime NgayHan { get; set; }
        public string MaBaoMat { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
